name: Check changed files and push report

on:
  push:
#  pull_request:
    branches:
    - main
    - second

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV
      - run: echo $GITHUB_ENV > files.log
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: nc_report.log
