name: Check changed files in parallel and push report

on:
  push:
#  pull_request:
    branches:
    - main
    - second

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          separator: ","

      - name: List all changed files
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}" >> changed-files.log

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: changed-files.log

