name: Check changed files in parallel and push report

on:
  push:
#  pull_request:
    branches:
    - main
    - second

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
  check:
    strategy:
      matrix:
          check-files: [datefile.txt, newtest.txt]
    runs-on: ubuntu-latest
    steps:
      - name: Check file for TABs
        run: |
            tab_str=`grep -P '\t' ${{ matrix.check-files }} | wc -l`
            echo "$tab_str strings with TABs in changed file: ${{ matrix.check-files }}" >> ${{ matrix.check-files }}.log
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.check-files }}.log
